pw_toolchain/rust: Introduce support for alloc
There's support for stdlibs_none and stdlibs_core_only
essentially.  We need to support alloc too.  This
fixes a compile with the ARMv8 MCU target when it requires
alloc support.

error[E0463]: can't find crate for `alloc`
 --> external/rules_rust++crate+crates_no_std__allocator-api2-0.2.21/src/lib.rs:7:1
  |
7 | extern crate alloc as alloc_crate;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

BUG=453730584
TEST=compile library for ARMv8 MCU

Change-Id: I9fc9d0c022ed865bfea059e084cce8edc0b9f834
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/354593
Docs-Not-Needed: Armando Montanez <amontanez@google.com>
Copybara-Verified: Copybara Prod <copybara-worker-blackhole@google.com>
Reviewed-by: Erik Gilling <konkers@google.com>
Pigweed-Auto-Submit: Gurchetan Singh <gurchetansingh@google.com>
Docs-Not-Needed: Erik Gilling <konkers@google.com>
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Commit-Queue: Gurchetan Singh <gurchetansingh@google.com>