Revert "pw_trace_tokenized: Use InlineVarLenEntryQueue for trace buffer"
This reverts commit 8d47bd657be092b08a50ee2835a4ad4af9cbec42.

Reason for revert: Fetching trace data via pw_transfer fails with error:
pw_transfer.client.Error: Transfer 1 failed with status Status.INTERNAL

Original change's description:
> pw_trace_tokenized: Use InlineVarLenEntryQueue for trace buffer
>
> Bug: 437155622
> Change-Id: Ic32231e879232076c8a52325ccf7f316422386c5
> Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/316736
> Reviewed-by: Wyatt Hepler <hepler@google.com>
> Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
> Tests-Not-Needed: Aaron Green <aarongreen@google.com>
> Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
> Commit-Queue: Aaron Green <aarongreen@google.com>

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 437155622
Change-Id: Id0f3dea0677ba9429070c74f09e9e0a81a1fdf6c
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/338592
Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Reviewed-by: Jonathon Reinhart <jrreinhart@google.com>
Reviewed-by: Aaron Green <aarongreen@google.com>
Commit-Queue: Austin Foxley <afoxley@google.com>
Pigweed-Auto-Submit: Austin Foxley <afoxley@google.com>
Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>